README.md, package.json, src/defaultConfig.ts, src/module.ts, src/runtime/server/middleware/corsHandler.ts, src/types.ts, yarn.lock
=> feat: add cors middleware

README.md, docs/content/1.getting-started/1.quick-start.md
=> docs: add Stackblitz demo

package.json, src/runtime/server/middleware/rateLimiter.ts, yarn.lock
=> feat: switched to unstorage

README.md, docs/content/1.getting-started/2.configuration.md, docs/content/1.index.md, src/defaultConfig.ts, src/module.ts, src/runtime/nitro.ts, src/types.ts
=> feat: hide powered by

README.md, docs/content/1.getting-started/2.configuration.md, docs/content/1.index.md, docs/content/2.middlewares/6.allowed-methods-restricter.md, src/defaultConfig.ts, src/module.ts, src/runtime/server/middleware/allowedMethodsRestricter.ts, src/types.ts
=> feat: add allowedMethodsRestricter

docs/content/1.getting-started/2.configuration.md
This change corrects the default headers' config in the docs as the route is currently different there than in the actual default config. :)
=> docs: correct headers default config in docs

package.json, yarn.lock
=> feat: bump to nuxt 3.0.0

README.md
Updates package manager in the 'Development' section of the readme file.
=> chore: replace `npm` with `yarn` in readme

package.json, src/runtime/server/middleware/rateLimiter.ts, yarn.lock
- Adds `@types/memory-cache`
- Adds `await` to `cachedLimiter.removeTokens(1)`
- Type casts `cache.get(ip)` to provide autocomplete
=> refactor: minor improvements in `rateLimiter`

docs/content/1.getting-started/1.quick-start.md
=> docs: add video tutorial

docs/content/1.getting-started/2.configuration.md, docs/content/2.middlewares/2.request-size-limiter.md, docs/content/2.middlewares/3.rate-limiter.md, docs/content/2.middlewares/4.xss-validator.md, docs/content/2.middlewares/6.allowed-methods-restricter.md, playground/nuxt.config.ts, src/defaultConfig.ts, src/runtime/server/middleware/allowedMethodsRestricter.ts, src/runtime/server/middleware/rateLimiter.ts, src/runtime/server/middleware/requestSizeLimiter.ts, src/runtime/server/middleware/xssValidator.ts, src/types.ts
=> feat: optional throw error

src/module.ts
Hi. This should fix https://github.com/Baroshem/nuxt-security/issues/42 by ensuring server utils are not being externalized.
=> fix: add runtime dir to nitro inline array

package.json, stackblitz/.gitignore, stackblitz/README.md, stackblitz/app.vue, stackblitz/nuxt.config.ts, stackblitz/package.json, stackblitz/tsconfig.json
=> docs: add stackblitz to repo

src/runtime/nitro.ts
=> fix: nuxt 3.1.X x-powered-by

.stackblitz/package.json, .stackblitz/yarn.lock, package.json, yarn.lock
=> chore: bump nuxt to 3.2.0

docs/content/3.good-practices/9.use-security-checklists.md
=> docs: use security checklists

README.md, docs/content/1.index.md, docs/content/2.security/5.cors-handler.md, docs/content/_theme.yml, playground/pages/index.vue, src/defaultConfig.ts, src/module.ts, src/runtime/nitro/plugins/cspSsg.ts, src/runtime/server/middleware/corsHandler.ts, src/types.ts
=> chore: small corrections before release

package.json, src/defaultConfig.ts, src/module.ts
=> feat: #118 cors default origin

README.md, docs/content/1.getting-started/2.configuration.md, docs/content/1.index.md, docs/content/2.security/1.headers.md, playground/app.vue, src/defaultConfig.ts, src/headers.ts, src/types.ts
=> feat: #117 add permisions policy

src/module.ts, src/runtime/server/middleware/basicAuth.ts
=> fix: basic auth

.stackblitz/nuxt.config.ts, docs/content/1.getting-started/1.setup.md, docs/content/1.getting-started/2.configuration.md, docs/content/2.security/1.headers.md, docs/content/2.security/2.request-size-limiter.md, docs/content/2.security/3.rate-limiter.md, docs/content/2.security/4.xss-validator.md, docs/content/2.security/5.cors-handler.md, docs/content/2.security/6.allowed-methods-restricter.md, docs/content/2.security/7.basic-auth.md, playground/nuxt.config.ts, playground/pages/secret.vue, src/defaultConfig.ts, src/module.ts, src/runtime/server/middleware/allowedMethodsRestricter.ts, src/runtime/server/middleware/basicAuth.ts, src/runtime/server/middleware/corsHandler.ts, src/runtime/server/middleware/rateLimiter.ts, src/runtime/server/middleware/requestSizeLimiter.ts, src/runtime/server/middleware/xssValidator.ts, src/types.ts
=> feat: #109 routeRules support

docs/content/2.security/1.headers.md
A typo fix in 2.security/1.headers.md
`routeRoules` to `routeRules`
Just a small documentation change
=> docs: fix typo

docs/content/2.security/1.headers.md
Correcting the value indicated in the [Headers](https://nuxt-security.vercel.app/security/headers#permissions-policy) section of the docs to be consistent with the [Configuration](https://nuxt-security.vercel.app/getting-started/configuration#default-configuration) section, and most importantly, with the actual default in the code: https://github.com/Baroshem/nuxt-security/blob/f02e7026cc4191080067b6ba2e944ce0ec84d1ed/src/defaultConfig.ts#L45-L51
=> fix(docs): default value for Permissions-Policy

README.md
Added install options to README.md
=> Install options

src/runtime/server/middleware/xssValidator.ts
=> fix #185: errors in xss validation

package.json
Allows to make use of `corepack` to just run `yarn` and have the correct version of yarn being executed.
=> chore(package): specify manager

docs/content/1.documentation/1.getting-started/2.configuration.md
See https://github.com/Baroshem/nuxt-security/discussions/198#discussioncomment-7130655.
=> docs(configuration): add layer overriding instructions

src/types/index.ts
=> fix(csrf): replace CSRF option `false` with `boolean`

docs/content/1.documentation/5.advanced/2.faq.md, docs/content/1.documentation/5.advanced/3.strict-csp.md
Extend the FAQ section with Quick Reference Guides for
- Cloudflare
- Firebase
- Paypal
- Prismic
- Stripe
=> feat(doc): extend FAQ with Prismic

docs/content/1.documentation/2.headers/3.crossOriginEmbedderPolicy.md
Mark 'require-corp' as the default, so the docs are in line with the actual default value.
Mark 'require-corp' as the default, so the docs are in line with the actual default value.
=> docs: correct default for crossOriginEmbedderPolicy

docs/content/1.documentation/1.getting-started/3.usage.md
Hi :wave: this PR fix #365 , i forgot to update the documentation after refactoring my PR
=> docs: fix the example for runtime hooks

src/runtime/server/middleware/xssValidator.ts, test/xssValidator.test.ts
- [x ] New feature (a non-breaking change which adds functionality)
The original version doesn't support FormData, resulting in blocking all FormData requests. This pull request adds a feature to enhance FormData support.
Fix #400
=> Enhance FormData with XSS validation feature.

docs/content/1.documentation/2.headers/1.csp.md
Fixes a comparision in the documentation example
=> Update 1.csp.md - FIX comparison in docs

docs/content/1.documentation/1.getting-started/2.configuration.md
While I was reading the "Configuration" steps for this module I noticed a small typo in the documentation and decided to fix it.
This change ensures that the project documentation is correct.
=> Fixed small typo found in the documentation

docs/content/1.documentation/5.advanced/2.faq.md
Closes #447 
The FAQ in the documentation for using in `--host` mode wrongly suggests to set `strictTransportSecurity: true`. This value does not exist.
This PR updates the docs.
=> fix(docs): update FAQ section on `--host` mode

.stackblitz/package.json, .stackblitz/yarn.lock, docs/package.json, docs/yarn.lock, package.json
Closes #462 
This patches v2.0.0-rc.1 by fixing the missing dependency in the rollup build step.
=> fix(core): rollup error

package.json
=> fix(rc): bump package version

docs/content/1.documentation/3.middleware/6.basic-auth.md
- [x ] Bug fix (a non-breaking change which fixes an issue)
Just a small typo fix
- [ x] I have updated the documentation accordingly.
=> Typo fix in docs

docs/content/1.documentation/2.headers/1.csp.md
minor correction of the indentation in the docs
=> Indentation corrected

docs/content/1.documentation/1.getting-started/1.setup.md, playground/nuxt.config.ts, src/defaultConfig.ts
=> feat-#487: local dev with nuxt devtools

docs/content/1.documentation/2.headers/3.crossOriginEmbedderPolicy.md
Clarified when "require-corp" is the default value. (documentation change)
=> Clarified when "require-corp" is the default value (documentation change)

docs/content/1.documentation/5.advanced/7.improve-security.md
fix broken url `/headers/xxx` -> `/documentation/headers/xxx`
=> docs: fix broken links

.github/workflows/pr-pkg-new.yml
Closes #489
This PR enables 'Continuous Releases' via the pr.pkg.new Github action on the repo.
With this action, approved PRs are now pre-published without publishing anything to NPM. This enables users to access features and bug-fixes without the need to wait for release cycles using npm or pull request merges.
See https://github.com/stackblitz-labs/pkg.pr.new for more information.
=> feat(core): Continuous Releases

docs/package.json, playground/nuxt.config.ts, playground/pages/index.vue, src/module.ts
Resolves #559
This PR ensures that `console.log` statements are not removed in `dev` mode, as this is the expected standard beahviour.
=> fix(core): do not remove loggers in dev mode

docs/content/1.getting-started/1.installation.md, docs/content/1.getting-started/2.configuration.md, docs/content/1.getting-started/3.usage.md, docs/content/2.headers/1.csp.md, docs/content/4.utils/3.subresource-integrity.md, docs/content/5.advanced/3.strict-csp.md, docs/content/5.advanced/7.improve-security.md
A lot of links point to `/documentation/...` route which opens a blank page.
=> fix(docs): broken links

.github/ISSUE_TEMPLATE/bug-report.yml
=> bug reports: update placeholders

README.md
The link in `README.md` for the license returns a "page not found" error.
This PR updates the license link in `README.md` to correctly link to `LICENSE.md` by including the `.md` suffix.
=> docs(fix): readme license link

LICENSE.md
Updates the year in `LICENSE.md` to use the 'present' style to avoid yearly updates. 
Sets the initial year as to original year set out in 18a0d3a69f33a778c97abdff56b5819e763614c2.
=> [ci skip] docs: update license year

.github/ISSUE_TEMPLATE/question.md
This pull request includes a small change to the `.github/ISSUE_TEMPLATE/question.md` file. The change updates the documentation links to direct users to the actual documentation and removes the hint of the now deprecated #modules discord channel.
Documentation update:
* [`.github/ISSUE_TEMPLATE/question.md`](diffhunk://#diff-9fba10a9fc5e1302774ec9dbbc8e8517954450b6fe6ba5af6724a410d9b9d9e6L10-R11): Updated the documentation link to `https://nuxt-security.vercel.app/` and removed the reference to the Discord channel.
=> Update GitHub question issue template with the correct link

src/runtime/server/middleware/basicAuth.ts
Updated the basicAuth middleware to pass event context into `useRuntimeConfig` composable, ensuring proper access to private settings. Resolves #595
=> Refactor basicAuth middleware to use runtime configuration correctly

.github/workflows/ci.yml, package.json, src/utils/crypto.ts, yarn.lock
Node 18 is EOL.
Vite 7, which will be a transitive dependency when the lockfile is updated, does not support Node 18 anymore.
Updating the lockfile is required for testing the latest nitropack version so that PR https://github.com/Baroshem/nuxt-security/pull/634 makes sense.
=> feat(node)!: upgrade to v20
