docs/content/1.getting-started/2.configuration.md
docs/content/2.middlewares/1.headers.md
src/defaultConfig.ts
src/headers.ts
src/module.ts
src/types.ts

This change aims to:
- update the misleading `| boolean` in types where `true` is actually an unacceptable value that would break the module
- provide better typing for certain headers' values
- enable modifying only picked parts of complex headers like Content Security Policy
Especially the very last point pushed me towards proposing this change as I found it really cumbersome to copy, modify and paste the original value for CSP when trying to add [Nuxt Image](https://v1.image.nuxtjs.org/get-started/) using Cloudinary.
Change should be fully backwards-compatible (see using the string value when it's given instead of an object) - if there is any breaking change - I'll definitely rethink it and try to improve this proposal.

feat: improve headers config and types

---

docs/content/1.getting-started/2.configuration.md
docs/content/2.middlewares/1.headers.md
src/defaultConfig.ts
src/types.ts

resolves https://github.com/Baroshem/nuxt-security/issues/66
The issue in the linked issue that this module is outputting `X-XSS-Protection` with the value of a number, which is not valid (it should be a string). This is normally not an issue but vercel complains when it sees the generate override config in `.vercel/output/config.json`

fix: xss protection header should be a string

---

docs/content/1.getting-started/2.configuration.md
src/defaultConfig.ts
src/module.ts
src/types.ts

feat: add enabled config option

---

README.md
docs/content/1.getting-started/1.quick-start.md
src/module.ts

This PR is related to #87.
I've implemented options from the module setup.

[Fix] Module Options

---

docs/content/3.good-practices/3.use-eslint-security-plugins.md

Use correct plugin name. i.e. "anti-trojan-source" instead of "security-node"
- [] My change requires a change to the documentation.

[documentation] Fixed typo for "anti-trojan-source"

---

docs/content/2.security/5.cors-handler.md
package.json
src/defaultConfig.ts
src/module.ts
src/runtime/server/middleware/corsHandler.ts
src/types.ts
yarn.lock

feat: #114 migrate cors

---

README.md
docs/content/2.security/7.basic-auth.md
src/runtime/server/middleware/basicAuth.ts
src/types.ts
test/basicAuth.test.ts
test/fixtures/basicAuth/nuxt.config.ts
test/fixtures/basicAuth/server/api/hello.ts

New exclude option for basic auth feature. Exclude option can enable request to some routes through basic auth middleware.
For example, to allow access to `/api` routes. Also access to `/api` routes is required for using basic auth with nuxt-content. More information is in issue below.
Resolves: https://github.com/Baroshem/nuxt-security/issues/144

feat: basic auth exclude routes option

---

package.json

Defines the correct typings file in the `types` field, and adds the same field inside the `exports` for correct TypeScript module resolution support.
This PR solves the type resolution for this package, previously it would fail and instead, TypeScript would try to load (or rather, infer) the types from the `./dist/module.mjs` file rather than loading the `types` property in `package.json`, this is, after all, because the `exports` field overrides it.
This field is also order-sensitive, TypeScript will try to load the first condition on the object (the properties are, after all, conditions that are tested against in insertion order). This will not change the behavior when loading the package from Node.js, as `types` is not a valid condition for the runtime. You can see a PR with a detailed …

fix: add compatibility for modern module resolutions

---

docs/content/2.security/1.headers.md
src/defaultConfig.ts
src/module.ts
src/runtime/nitro/plugins/cspNonce.ts
src/runtime/server/middleware/cspNonceHandler.ts
src/types.ts
test/fixtures/nonce/app.vue
test/fixtures/nonce/nuxt.config.ts
test/fixtures/nonce/package.json
test/fixtures/nonce/pages/index.vue
test/fixtures/nonce/pages/use-head.vue
test/fixtures/nonce/public/external.js
test/fixtures/nonce/public/loader.js
test/fixtures/nonce/server/api/generated-script.ts
test/fixtures/nonce/server/api/nonce-exempt.ts
test/nonce.test.ts

Add support for `nonce` values in CSP. 
Regenerates nonce on every request, but allows overriding this behaviour per route. 
I'm using this in production to implement a [strict csp using nonce](https://web.dev/strict-csp/#what-is-a-strict-content-security-policy).
Resolves: #136

feat: add `nonce` support to csp

---

docs/content/2.security/1.headers.md
src/module.ts
src/runtime/composables/nonce.ts
src/runtime/nitro/plugins/cspNonce.ts
src/runtime/server/middleware/cspNonceHandler.ts
test/fixtures/nonce/app.vue
test/fixtures/nonce/nuxt.config.ts
test/fixtures/nonce/pages/use-head.vue
test/fixtures/nonce/pages/with-inline-script.vue
test/fixtures/nonce/pages/with-styling.vue
test/fixtures/nonce/public/external.js
test/fixtures/nonce/public/loader.js
test/nonce.test.ts

When working with the recently introduced `nonce` feature I noticed some quirks that this PR aims to correct.
- `nonce`  attribute was not being applied to `<style>` elements, resulting in CSP violations
- when using `ssr` the nonce value could get out of sync
- using the `nonce` value directly is almost never needed, so the documentation should show that as well
Finally, I discovered strange behavior due to [an upstream bug in `unjs/unhead`](https://github.com/unjs/unhead/issues/136) when using nonce values.
- useHead tags are injected twice when using `nonce` and `ssr`
I've fixed these quirks and updated the tests and documentation accordingly to reflect these findings.

fix: nonce quirks when using `ssr`

---

src/types.ts

Add `throwError?: boolean;` to RequestSizeLimiter, RateLimiter, XssValidator types so nuxt.config.ts doesn't complain when you include it.
- [ x ] Bug fix (a non-breaking change which fixes an issue)
Add `throwError?: boolean;` to RequestSizeLimiter, RateLimiter, XssValidator types so nuxt.config.ts doesn't complain when you include it.
Resolves:
https://github.com/Baroshem/nuxt-security/issues/188

Add throwError?: boolean to types that need it

---

docs/content/1.getting-started/2.configuration.md

This PR adds a section for `trpc-nuxt`, specifically on how to make the `CSRF` functionality work.

docs: added trpc-nuxt configuration section

---

docs/content/2.security/3.rate-limiter.md

Fix no comma in `fireImediately: false`
Currently there are no comma after `fireImmediately: false`.

Update 3.rate-limiter.md fix comma

---

src/module.ts

Use an individual export so that not the whole dependency is imported.

chore(defu): do not use default export

---

docs/content/2.security/3.rate-limiter.md
docs/content/2.security/4.xss-validator.md

Add missing commas to Documentation of rate limiter and xss validator

Add Missing commas inside the docs examples

---

docs/content/1.documentation/2.headers/1.csp.md

As requested in https://github.com/Baroshem/nuxt-security/issues/239#issuecomment-1757724311

chore: update `nonce` docs about `unsafe-inline` during development

---

docs/content/1.documentation/5.advanced/2.faq.md

Add a new doc to explain how to override default headers on a specific route in Nuxt.js by using 'routeRules' and provide alternative methods using middleware and 'NuxtLink' with the 'external' attribute.
Resolves: #229

Add documentation for updating headers on a specific route

---

src/module.ts

Ensure internal types of module are exported for dependent projects. Resolves: #263 
Tests not applicable because this is purely exposing types. Nuxt module builder reexports exported types via the module dist's types.d.{ts, mts}.

Ensure all types are exported

---

docs/content/1.documentation/1.getting-started/2.configuration.md
docs/content/1.documentation/2.headers/1.csp.md
src/runtime/composables/nonce.ts
src/runtime/server/middleware/cspNonceHandler.ts
src/types/index.ts
src/types/middlewares.ts
test/nonce.test.ts

These changes disable the possibility for the server to use a pre-determined nonce.
With these changes, the module now adheres to the W3C specs on CSP para 7.1: Nonce Reuse (https://www.w3.org/TR/CSP3/#security-nonces).
The modifications to the code include:
- disallowing the ability to set nonces on the server via cookie
- disallowing the possiblity to set nonces other than through cryptographically secure methods
- suppressing the former 'check' mode
- not sending nonces via cookie to the frontend

improve CSP compliance

---

.stackblitz/.gitignore
src/module.ts
src/runtime/nitro/plugins/02-cspSsg.ts

Extend CSP support of SSG applications:
- parse all HTML sections
- hashes for inline styles
- hashes for external scripts
- CSP headers for static nitro presets
This PR extends how we support CSP for SSG applications.
Currently, in SSG mode, Nuxt Security only searches for inline scripts in the `bodyAppend` section of Ntro's html rendering step.
With this PR, the following functionalities are added:
- Scan all sections of the `html` being rendered by Nitro. 
This covers the case where scripts or styles are added to the `<head>` tag, or to other parts of the `<body>` section.
- Scan inline styles, and add SHA hashes to the `style-src` policy. 
This covers the case where, in the absence of the `unsafe-inline` value, CSP requires that inline styles are individually authorized.
- Scan …

feat(csp): Extend CSP support of SSG mode

---

src/defaultConfig.ts
src/runtime/nitro/plugins/02-cspSsg.ts
src/types/index.ts

This PR adds an `ssg: hashStyles` option in the `ModuleOptions` interface.
The background for this option is that CSP hashes do not carry the exact same meaning for `<script>` and for `<style>` tags.
- For the `script-src` policy, when `'strict-dynamic'` is enabled, new `<scripts>` inserted by hashed scripts will be *allowed*
- For the `style-src` policy, there is no `'strict-dynamic'` option, and therefore new `<styles>` inserted by hashed scripts will be *disallowed*.
As a result, a user who is not in control of how scripts dynamically insert styles, may typically want to introduce script hashes but exclude style hashes.

feat(csp): add hashStyles option for SSG

---

docs/content/1.documentation/2.headers/1.csp.md
docs/content/1.documentation/5.advanced/3.strict-csp.md
src/defaultConfig.ts
src/runtime/nitro/plugins/02-cspSsg.ts
src/types/index.ts

Modify & Update the CSP documentation section
Create an Advanced Section on CSP with knowledge base

docs(csp): Documentation on CSP

---

docs/content/1.documentation/1.getting-started/2.configuration.md

A user must be able to skip adding hashes to the 'style-src' policy
This is because adding even one hash cancels 'unsafe-inline'
Note: this is only for SSG

feat(csp): hashStyles option

---

docs/content/1.documentation/2.headers/1.csp.md
docs/content/1.documentation/2.headers/2.permissions-policy.md
docs/content/1.documentation/2.headers/8.strictTransportSecurity.md

docs: update route rules docs

---

playground/nuxt.config.ts
src/module.ts

Fixes #319
Extend interface `nuxt/schema` instead of `@nuxt/schema` to avoid overwritting type declarations of other modules.
The regression was introduced in rc5

Fix(types): do not overwrite @nuxt/schema

---

src/module.ts
src/runtime/nitro/plugins/02-securityHeaders.ts
test/fixtures/perRoute/nuxt.config.ts
test/fixtures/perRoute/pages/preserve-middleware/deep/page.vue
test/fixtures/perRoute/pages/preserve-middleware/index.vue
test/fixtures/perRoute/server/middleware/preserve-test.ts
test/perRoute.test.ts

Fixes #321
This PR reverts a breaking change introduced by rc.5
Previously to rc.5, setting a security header value to `false` did not modify the existing header value.
With rc.5, setting a security header value to false removed the header.
We are reverting to pre-rc.5 behaviour, i.e. we semantically translate `false` to `do not set` instead of `do not send`.

fix: csp false in rc5 removes custom csp header

---

docs/content/1.documentation/1.getting-started/1.setup.md

In Installation page below adding the module section, there is a "routeRoule" typo mistake

Documentation typo change from route roules to route rules

---

src/module.ts
test/perRoute.test.ts

Fixes #348
Fixes #335
This patch removes the cspSsgPresets functionality to temporarily solve issues #335 and #348, while we work on an alternative solution.
This patch is required after Nuxt 3.9.3 introduced protection against importing `@nuxt/kit` in Nitro plugins, which breaks `05-cspSsgPresets.ts` in our module.

Disable 05-cspSsgPresets

---

src/module.ts
src/runtime/nitro/plugins/02a-preprocessHtml.ts
src/runtime/nitro/plugins/03-subresourceIntegrity.ts
src/runtime/nitro/plugins/04-cspSsgHashes.ts
src/runtime/nitro/plugins/99-cspSsrNonce.ts
src/runtime/nitro/plugins/99b-recombineHtml.ts

Fixes #341
This is a first pass at mitigating cheerio performance issues reported in #341.
Instead of parsing and recombining multiple times the same HTML, we now parse it only once upfront, and recombine it at the end.
It is unlikely to be the best approach as we may prefer to not use Cheerio anymore and instead re-implement via regexes.
I'm proposing this patch as a quick fix in the meantime so that Cloudflare users can mitigate issues.

Patch for cheerio performance

---

src/runtime/nitro/plugins/02a-preprocessHtml.ts

Fixes #341 
This is an additional patch to again improve Cheerio. Following review of Cheerio's documentation, we now
- use the htmlparser-2 option instead of parse5
- load the slim version of cheerio
This is the second optimization patch related to Cheerio performance issues reported in #341

Further optimization patch for cheerio

---

docs/content/1.documentation/5.advanced/1.good-practices.md

Describes uses of good state and bad state. Also describes recommended usage of useState. 
Resolves: #361 
Documentation only

docs: handling state with care

---

src/runtime/nitro/plugins/00-context.ts

Fixes my issue https://github.com/Baroshem/nuxt-security/issues/373
It seems like not explicitly importing setHeader (and i assume also removeResponseHeader)
prevents them from beeing in the output of the nuxt build.
It solved the issue that setting the headers via a nitro plugin with the hook 'nuxt-security:headers' does not work.
Resolves: #373
I have not added tests, since it is only a missing import

fix: add explicit imports for setHeader and removeResponseHeader in 00-context.ts

---

docs/content/1.documentation/3.middleware/3.xss-validator.md
src/runtime/server/middleware/xssValidator.ts
src/types/middlewares.ts

resolves #206
js-xss has [`escapeHtml`option](https://github.com/leizongmin/js-xss/blob/master/lib/index.js#L18), [by default](https://github.com/leizongmin/js-xss/blob/master/lib/default.js#L158) `<` is replaced by `&lt;` and `>` by `&gt;`
This pull request allows dev to easily disable this feature
Before this fail:
```js
fetch('/api/test', { method: 'POST', body: JSON.stringify({ value: "ok ->" }), headers: { 'Content-Type': 'application/json' } })
```
Now, if `xssValidator.escapeHtml` is set to false it works

feat: add escapeHtml option to XssValidator

---

docs/content/1.documentation/3.middleware/3.xss-validator.md
src/defaultConfig.ts
src/module.ts
src/runtime/server/middleware/xssValidator.ts
src/runtime/utils/methods.ts
src/types/middlewares.ts

Partially resolves #364
This PR introduces a way for users to choose which methods they would like to add for the XSS validator to work. 
Will add later.

feat: allow users to configure methods for XSSValidator

---

src/runtime/nitro/plugins/04-cspSsgHashes.ts
test/ssgHashes.test.ts

Closes #329 
Removes the `frame-ancestors` CSP directive in SSG mode.
As stated in the [MDN Doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors), this directive is not supported in the meta element.
Fixes Chrome complaining of the same:

fix(ssg): remove frame-ancestors from meta

---

src/runtime/nitro/plugins/04-cspSsgHashes.ts

By default `cheerio.load` will introduce `<html>`, `<head>` and `<body>` elements if they are not present in the argument. This causes the following code to add duplicate `<html>`, `<head>` and `<body>` elements inside the already existing `<head>`.
See [their docs](https://cheerio.js.org/docs/basics/loading#load).
This PR fixes this by disabling the default behaviour of the load function.

fix(ssg): generate meta tag without html,head,body tags

---

src/runtime/nitro/plugins/02a-preprocessHtml.ts

Fixes #393
Currently, cheerio uses the default setting of `decodeEntities: true` when parsing the HTML document.
This modifies the encoding of special characters (e.g. German umlauts).
This PR changes the option to `decodeEntities: false`, which prevents cheerio from modifying the original source.

fix(core): do not decode entities in HTML

---

package.json
src/runtime/nitro/plugins/03-subresourceIntegrity.ts
yarn.lock

Fixes #395
Subresource Integrity for SSR is broken when using Nuxt 3.9+
This is related to the way Nuxt 3.9+ bundles strings, which is now using Uint8Array buffers.
This PR fixes this issue by:
1- correctly fetching SRI hashes in Uint8Array format
2- upgrading the module dependency to Nuxt 3.10

sri: fetch buffers from storage and convert to object

---

docs/content/1.documentation/5.advanced/2.faq.md

This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
In [Nuxt v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) we added support for `import.meta.*` (see [original PR](https://github.com/nuxt/nuxt/pull/22428)) and we've been gradually updating docs and moving across from the old `process.*` patterned variables.
As I'm sure you're aware, these variables are replaced at build-time and enable tree-shaking in bundled code.
This change affects _runtime_ code (that is, that is processed by the Nuxt bundler, like vite or webpack) rather than code running in Node. So it really doesn't matter what the string is, but it makes more sense in an ESM-world to use `import.meta` rather than `process`.
(It …

fix: opt in to `import.meta.*` properties

---

src/runtime/nitro/plugins/99-cspSsrNonce.ts

Fix #407 
Hey :wave: 
This PR change the way the SSR CSP plugin works. Before that, it was relying on the configuration. 
This Pr moves the replacement of the nonce placeholder to `beforeResponse`, so it can parse and rewrite the content security policy header after it was set (by runtime hooks and the security configuration/build-time config)

fix: set nonce in response headers instead of using configuration

---

README.md
docs/content/1.documentation/1.getting-started/1.setup.md

This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏

docs: use new `nuxi module add` command in installation

---

docs/content/1.documentation/2.headers/1.csp.md
docs/content/1.documentation/5.advanced/3.strict-csp.md
package.json
yarn.lock

Modify notes to recommend `useScript`
For Nuxt version 3.11 and above, `useScript` allows to insert any external script in a CSP-compatible way.
Update documentation to recommend `useScript`.

update(doc): recommend useScript for Nuxt 3.11+

---

package.json
yarn.lock

Bump unplugin-remove to remove warning withing nuxt compilation
This was addressed today and the version was bumped to 1.0.2
Recent bump of unplugin-remove returns a lot of warnings(hunderds in our case) during nuxt compilation: https://github.com/Talljack/unplugin-remove/issues/139
Warning:
```[plugin unplugin-remove-console-debugger] Sourcemap is likely to be incorrect: a plugin (unplugin-remove-console-debugger) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help```
I don't think anything of the checklist applies, regression should be covered in the current test.

chore: bump unplugin-remove to fix sourcemap warnings

---

playground/nuxt.config.ts
src/module.ts
src/runtime/nitro/plugins/50-subresourceIntegrity.ts
src/runtime/utils/hashes.ts

This PR brings a technical rewrite of the way we save SRI hashes at build time.
Previously, the way we saved SRI hashes was hacky. We were writing the hashes on the drive under the `.nuxt` build-time directory, which was necessary for SSG rendering of integrity hashes. But because this directory is not available in the server context in SSR mode, we also copied them to the server assets output folder. Then we relied on `useStorage` to retrieve the hashes, and depending whether the context was SSR or SSG, we had to look either into the `build` folder or `assets` folder. Because the output was in JSON format, we encountered issues when Nitropack changed the format of raw assets in JSON format (most notably #395).
With this rewrite, we now use the native Nuxt Virtual File System to inject …

feat(core): use virtual file system for SRI

---

docs/nuxt.config.ts
docs/package.json
docs/yarn.lock
package.json
src/module.ts
src/runtime/nitro/plugins/90-prerenderedHeaders.ts

This allows to deploy docs with Nuxt Security enabled.
This is a first step towards obtaining a security score that can be displayed on the site: see #446

feat(docs): add security to docs

---

src/runtime/nitro/plugins/60-recombineHtml.ts
test/ssgHashes.test.ts

Closes #444
Currently we insert the CSP meta tag as the first element, to make sure it is read by the UA as soon as possible.
However the [W3C spec for HTML5](https://html.spec.whatwg.org/multipage/semantics.html#charset) mentions that the charset meta tag should be the first in `head`
This PR ensures that the CSP meta tag is inserted right after the charset meta tag, if it exists.

fix(csp): ensure charset meta at top of head

---

src/module.ts
src/types/middlewares.ts
test/fixtures/storageOptions/app.vue
test/fixtures/storageOptions/nuxt.config.ts
test/fixtures/storageOptions/package.json
test/fixtures/storageOptions/pages/index.vue
test/storageOptions.test.ts

Closes #433
The Rate Limiter options need to be spread in order to support all the `unstorage` drivers.
Previously, only the `options` property could be provided to the underlying driver, because this driver has only one property with the name `options`.
With this PR, any property name can be provided under the `options` property.

fix(core): spread storage options

---

docs/content/1.documentation/2.headers/1.csp.md
src/types/headers.ts

The navigate-to directive was removed from the CSP spec, and is therefore not needed to be configurable. This comments it out so in case a new version of it resurfaces it could easily be added back.

fix: remove navigate-to csp directive

---

docs/content/1.documentation/3.middleware/7.csrf.md

Closes https://github.com/Baroshem/nuxt-security/issues/469
This updates docs with usage of csrf protection on a per route basis direclty using csurf

add per route csrf to docs

---

src/runtime/nitro/plugins/30-cspSsgHashes.ts
test/fixtures/ssgHashes/nuxt.config.ts
test/fixtures/ssgHashes/pages/inline-script-with-linebreak.vue
test/fixtures/ssgHashes/pages/inline-style-with-linebreak.vue
test/ssgHashes.test.ts

This PR updates the regular expressions in the `30-cspSsgHashes.ts` file. The previous regular expression was not correctly capturing the content of inline script and style tags in all scenarios. 
The old regular expression for inline scripts:
```typescript
const INLINE_SCRIPT_RE = /<script(?![^>]*?\bsrc="[\w:.\-\\/]+")[^>]*>(.*?)<\/script>/gi
```
The updated regular expression:
```typescript
const INLINE_SCRIPT_RE = /<script(?![^>]*?\bsrc="[\w:.\-\\/]+")[^>]*>([\s\S]*?)<\/script>/gi;
```
The change from `(.*?)` to `([\s\S]*?)` ensures that the regular expression matches any character, including newlines, between the `<script>` and `</script>` tags. This change improves the accuracy of inline script content capture, ensuring that our CSP security hashes are correctly generated for all …

fix(csp): inline script/style have whitespace character

---

docs/nuxt.config.ts

The documentation page is broken with the new `strict` mode.
In rc-9, the `strict` mode denies unsafe-inline styles by default, which are required by pinceau.
This patch updates the documentation setup to allow pinceau runtime hydration.

fix(docs): csp denial of pinceau styles runtime hydration

---

docs/content/1.documentation/2.headers/1.csp.md
src/runtime/nitro/plugins/40-cspSsrNonce.ts

Allows to use `"'nonce-{{nonce}}'"` placeholder on `style-src` policy in development.
Resolves discussion #454.
Not sure how to run tests for development mode.

feat(csp): support style nonce in development

---

docs/content/1.documentation/5.advanced/3.strict-csp.md

This PR is only a doc change on how to load 3rd-party scripts.
Instead of `useScript`, we recommend using the Nuxt Scripts module

feat(doc): introduce Nuxt Scripts as alternative to `useScript`

---

src/module.ts
src/runtime/nitro/plugins/00-routeRules.ts
src/utils/originRegExpSerde.ts

fix #497 
`useRuntimeConfig()` get runtimeConfig from `process.env`, which `JSON.stringify`ed the runtimeConfig, and also `JSON.stringify(RegExp)` is `'{}'`, so when `corsHandler.origin` is `RegExp[]`, it doesn't work.
I add custom `toJSON` method to `RegExp` members inside `corsHandler.origin`, and parse it back to `RegExp` when assign runtimeConfig to `appSecurityOptions`.
I'm not sure if there is a better solution. Tell me if it exists.

fix: ensure RegExp[] origin can be passed to appSecurityOptions

---

docs/content/1.documentation/5.advanced/2.faq.md

docs: update information about Nuxt Image

---

package.json
yarn.lock

(from @danielroe)
Previous versions of @nuxt/module-builder produced incorrect types for files in the runtime/ directory. Specifically, a .d.ts declaration paired with a .mjs file. This isn't correct - it should be either .d.mts and .mjs or .d.ts and .js.
For maximum compatibility, @nuxt/module-builder v0.8 switched to .js extension for files in runtime/ directory.
With the latest Nuxt, this is now an error that removes correct plugin injection types.
Related PRs: https://github.com/nuxt/nuxt/pull/28480, https://github.com/nuxt/nuxt/pull/28593
See also https://github.com/nuxt/nuxt/issues/28672.

fix: update to latest @nuxt/module-builder

---

src/types/module.ts

Context: nuxt/nuxt#28332
`nuxt/schema` is a re-export of `@nuxt/schema` for users to use. Modules should not augment it, or it may end up overwriting the inferred types from `@nuxt/schema`.

 fix: augment @nuxt/schema rather than nuxt/schema

---

docs/content/1.documentation/3.middleware/4.cors-handler.md
src/runtime/server/middleware/corsHandler.ts
src/types/middlewares.ts
test/cors.test.ts
test/fixtures/cors/.nuxtrc
test/fixtures/cors/app.vue
test/fixtures/cors/nuxt.config.ts
test/fixtures/cors/package.json
test/fixtures/cors/pages/index.vue
test/fixtures/cors/pages/multi.vue
test/fixtures/cors/pages/regexp-multi.vue
test/fixtures/cors/pages/regexp-single.vue
test/fixtures/cors/pages/single.vue
test/fixtures/cors/pages/star.vue

Changes CORS options type to only allow serializable values. Add a new `useRegExp` property, that when set to true parses all origin values to a RegExp.

feat: support using regular expressions as CORS origin

---

src/defaultConfig.ts

Fix devtools being blocked when strict mode is enabled
88dbb4c4f7d10e05a01336d6bf409e1434aaabd5 the existing documentation has been removed, so it should work the same in strict mode as in none-strict mode 
ref: #487

fix: devtools being blocked in strict mode

---

docs/content/1.documentation/2.headers/1.csp.md
src/types/headers.ts
src/utils/headers.ts

Closes #526
Adds Trusted Types support to CSP policies

feat(csp): trusted types

---

src/module.ts

Fixes #535
This PR fixes an incorrect resolution of url paths in the sriHashes table, when a cdnURL option is passed to Nuxt with a path component

fix(sri): incorrect cdnUrl resolution

---

docs/content/1.documentation/2.headers/4.crossOriginOpenerPolicy.md

Moves mentioning a default value for COOP to the correct section in 'Available values'.

docs: mention correct default value for COOP

---

docs/content/1.documentation/1.getting-started/2.configuration.md
docs/content/1.documentation/4.utils/2.remove-console-loggers.md
src/defaultConfig.ts
src/module.ts
src/types/module.ts
yarn.lock

Fixes #533
This PR introduces an alternative method for removing `console.log` statements.
The new method is based on Vite's native functionalities, whereas the currently existing method is based on the external `unplugin-remove` package.
The `removeLoggers` option can now accept a new value, which is `true`. The new method is enabled when  `removeLoggers` is set to `true`, while the `unplugin-remove` package is still used when an object is used. This approach maintains compatibility with existing setups.
By default, `removeLoggers` is now set to `true`. This approach soft-deprecates the `unplugin-remove` method in all default setups.
We intend to fully deprecate the old approach in a future release.

feat(core): Vite native method to remove loggers

---

src/utils/headers.ts

Fixes #538
The `getHeadersApplicableToAllRessources` was previously returning an empty object `{}` when no eligible entry was found, which resulted in an empty `headers: {}` entry in the routeRules registry.
This could trigger a deployment failure in some Nitro presets (e.g. Vercel).
This PR ensures that no `headers` entry is created in the corresponding routeRule in that case, fixing the bug described in #538.

fix(core): do not create empty header entries in routeRules

---

.github/workflows/pr-pkg-new.yml

Closes #489
This PR enables 'Continuous Releases' via the pr.pkg.new Github action on the repo.
With this action, approved PRs are now pre-published without publishing anything to NPM. This enables users to access features and bug-fixes without the need to wait for release cycles using npm or pull request merges.
See https://github.com/stackblitz-labs/pkg.pr.new for more information.

feat(core): Continuous Releases

---

src/runtime/nitro/plugins/40-cspSsrNonce.ts

This PR fixes an issue in the `cspSsrNonce.ts` file where `element.replace` was called on non-string elements in the `html[section]` array during nonce injection. This caused a `TypeError: element.replace is not a function` in SSR mode when third-party libraries, such as PrimeVue, injected non-string elements.
The change introduces a type check to skip non-string elements, ensuring the rendering process doesn’t break and nonce attributes are properly applied to valid elements.
**Why is this change required?**
This resolves a crash in applications using Nuxt Security with SSR and libraries like PrimeVue.
Resolves: #564 
- Tests are not applicable in this case since the change addresses runtime behavior with specific third-party library interactions. I did, however, verify existing tests.

fix: #564 resolves issue with element.replace on non-string elements

---

.github/workflows/pr-pkg-new.yml
CHANGELOG.md
package.json
src/runtime/nitro/plugins/40-cspSsrNonce.ts

Hotfix release v2.1.3
- PrimeVue compatibility : #565 
- Add manual trigger for Continuous Releases

chore(release): 2.1.3

---

src/module.ts

Resolves #576
This PR changes the behaviour of the `removeLoggers` functionality to avoid potentially breaking third-party code.
Currently, the Nuxt Security module turns on Vite's build minification option by default. In some cases, it was found that this behaviour could have side-effects on third-party code.
With this PR, we do not modify the build `minify` option by default anymore.

fix(loggers): do not set minify option by default

---

src/runtime/nitro/plugins/40-cspSsrNonce.ts

Resolves #586 
For users utilizing Nuxt Image (with its option to provide custom nonces), Nuxt Security will override the user-defined nonce to ensure standard-complying, cryptographically secure nonces.
As a side note, it is worth deprecating the nonce property in Nuxt Image regardless due to the security concerns it brings with no proportionate benefit

fix(nonce): override user-defined nonce values with Nuxt Image

---

docs/content/3.middleware/1.rate-limiter.md
playground/nuxt.config.ts
playground/pages/rateLimit.vue
src/defaultConfig.ts
src/runtime/server/middleware/rateLimiter.ts
src/types/middlewares.ts
test/fixtures/rateLimiter/nuxt.config.ts
test/fixtures/rateLimiter/pages/whitelistBase.vue
test/fixtures/rateLimiter/pages/whitelistEmpty.vue
test/fixtures/rateLimiter/pages/whitelistNotListed.vue
test/rateLimiter.test.ts

Partially resolves #517 (to be discussed further for more advances use cases)

Add basic rate limiter whitelist (specific IPs only)

---

docs/content/2.headers/2.permissions-policy.md

This resolves #624. The URLs in the permissions policy must be enquoted, so they are correctly parsed into the permissions-policy header.

#624 - Update incorrect permissions policy docs

---

src/types/module.ts

This is apparently needed for Nuxt 4 typechecks when the new tsconfig references are used.
See https://github.com/maevsi/vibetype/actions/runs/15946276917/job/44980743382?pr=1997#step:7:1665
Depends on (merge after):
- https://github.com/Baroshem/nuxt-security/pull/640
Resolves https://github.com/Baroshem/nuxt-security/issues/637
Confirmed to be working in:
- https://github.com/maevsi/vibetype/pull/2022

fix(types): declare module `nitropack/types`
